version: '3.7'

services:
  mariadb:
    container_name: MDB
    hostname: mariadb.srcs_inception
    env_file: .env
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - anafonica
    volumes:
      - MDB_volume:/var/lib/mysql
    restart: always
    expose:
      - "3306"

  nginx:
    container_name: NGX
    env_file: .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    networks:
      - anafonica
    volumes:
      - WPS_volume:/var/www/wordpress
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"

  wordpress:
    container_name: WPS
    hostname: wordpress.srcs_inception
    env_file: .env
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - anafonica
    volumes:
      - WPS_volume:/var/www/wordpress
    depends_on:
      - mariadb
    restart: always
    expose:
      - "9000"

volumes:
  WPS_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/anamarqu/data/wordpress'
  MDB_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/anamarqu/data/mariadb'

networks:
  anafonica:
    driver: bridge
